dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python src/app.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: src/build
  on:
    branch: master